### ISSUE TITLE
Can you please remove some of the background images.

### ISSUE THREAD

**Issue by ChieF-TroN** [project-error/pe-basicloading#1]
Images labeled 1.jpg, 2.jpg, 5.jpg, and 6.jpg belong to All Day Role Play. Please remove them from this repo.

**Comment by RockySouthpaw** [comment]
Reference please? They look like in game images to me which are un edited afaik. I’m unsure how some role play server would have ownership of those. Is your role play server registered as an organization somewhere? 

They have mumble VoIP on the bottom right so it’s not as if an artist created said images.

I could actually go to these exact locations and take the same image 🤷‍♀️ not sure what the issue is.


Edit: To be clear, well check and make sure the images aren’t owned by anyone and if they are we have no issue removing them :). Thank you for opening the issue.

**Comment by ChieF-TroN** [comment]
Yes, I know, I took those screenshots myself. Taso is using my images, and this whole loading screen is extremely similar to the one that Taso made for ADRP about a year ago, now this is just updated version of it with mouse and tooltip support. I'm not going to complain about this loading screen as it is different enough not to request the whole thing to be taken down. But those are my images I can assure you.

**Comment by TasoOneAsia** [comment]
@ChieF-TroN Respond to my Discord messages regarding this as I don't think this is anything like the loading screen that I had worked on prior? I'm happy to hear out what your concerns are.

**Comment by RockySouthpaw** [comment]
If you took the images then no worries :). We’ll remove them when we get the chance. Thank you for opening the issue, as said previously

**Comment by ChieF-TroN** [comment]
I've sent proof over to Taso via discord regarding the images in question. I appreciate the cooperation on having them removed. I'll close this issue when the images have been removed.

**Comment by TasoOneAsia** [comment]
Can confirm that I had accidentally used some old resources that were in the same folder as the other screenshots. These are taken down with 4f9e0ab9c414f4f5aeb8948d49bf3dd5dc1d7013.
